language: go
sudo: required
services:
- docker
go: 1.7
cache:
  directories:
  - .node_modules/
before_install:
- openssl aes-256-cbc -K $encrypted_afb3f4a0fd37_key -iv $encrypted_afb3f4a0fd37_iv -in deploy_rsa.enc -out deploy_rsa -d
install:
- make
- nvm install node
- npm install -g npm
- npm i
script: |
  npm run build &&
  docker build -t ${DOCKER_USER}/docker-front -f Dockerfile_front . &&
  docker build -t ${DOCKER_USER}/docker-api -f Dockerfile_api .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && docker push ${DOCKER_USER}/docker-front && docker push ${DOCKER_USER}/docker-api
  fi
notifications:
  email: false
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "bash -s" 2>/dev/null -- < ./deploy.sh manager https://github.com/ViBiOh/docker-deploy.git vibioh.fr
  on:
    branch: master
