version: '2'

services:
  api:
    image: vibioh/dashboard-api
    command:
    - -ws
    - ^dashboard(?:-api)?\.(?:vibioh|l3miage)\.fr
    - -auth
    - /users
    environment:
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      DOCKER_VERSION: '1.24'
    labels:
      traefik.backend.healthcheck.path: '/health'
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: dashboard-api.vibioh.fr, dashboard-api.l3miage.fr'
      traefik.port: '1080'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/vibioh/code/src/github.com/ViBiOh/dashboard/users:/users:ro
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 33554432
    security_opt:
    - no-new-privileges

  front:
    image: vibioh/dashboard-front
    command:
    - -spa
    - -csp
    - "default-src 'self'; script-src 'self' 'unsafe-inline' www.google-analytics.com cdnjs.cloudflare.com ajax.googleapis.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com cdnjs.cloudflare.com; font-src 'self' fonts.gstatic.com cdnjs.cloudflare.com data: ; img-src 'self' www.google-analytics.com data: ; connect-src 'self' wss: dashboard-api.vibioh.fr dashboard-api.l3miage.fr;"
    labels:
      traefik.backend.healthcheck.path: '/health'
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: dashboard.vibioh.fr, dashboard.l3miage.fr'
      traefik.port: '1080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
