version: '2'

services:

  api:
    image: vibioh/dashboard-api
    command:
    - -prometheusMetricsHost
    - dashboard-api:1080
    - -ws
    - ^dashboard-api.vibioh.fr$$
    - -dockerVersion
    - '1.24'
    - -authUrl
    - https://auth.vibioh.fr
    - -users
    - vibioh:admin|eponae:multi
    - -corsHeaders
    - Content-Type,Authorization
    - -corsMethods
    - GET,POST,DELETE
    - -corsCredentials
    - -csp
    - "default-src 'self'; script-src 'unsafe-inline' ajax.googleapis.com cdnjs.cloudflare.com; style-src 'unsafe-inline' cdnjs.cloudflare.com fonts.googleapis.com; font-src data: fonts.gstatic.com cdnjs.cloudflare.com; img-src data:"
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: dashboard-api.vibioh.fr'
      traefik.protocol: 'https'
    traefik.port: '1080'
    networks:
      default:
        aliases:
        - dashboard-api
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

  front:
    image: vibioh/dashboard-front
    command:
    - -prometheusMetricsHost
    - dashboard:1080
    - -tls
    - -spa
    - -env
    - API_URL,WS_URL,AUTH_URL,BASIC_AUTH_ENABLED,GITHUB_OAUTH_CLIENT_ID,GITHUB_OAUTH_STATE,GITHUB_REDIRECT_URI
    - -csp
    - "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss: dashboard-api.vibioh.fr auth.vibioh.fr;"
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: dashboard.vibioh.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
    environment:
      API_URL: 'https://dashboard-api.vibioh.fr'
      WS_URL: 'wss://dashboard-api.vibioh.fr/ws'
      AUTH_URL: 'https://auth.vibioh.fr'
      BASIC_AUTH_ENABLED: 'false'
      GITHUB_OAUTH_STATE: '${GITHUB_OAUTH_STATE}'
      GITHUB_OAUTH_CLIENT_ID: '${GITHUB_OAUTH_CLIENT_ID}'
      GITHUB_REDIRECT_URI: 'https://dashboard.vibioh.fr/auth/github'
    networks:
      default:
        aliases:
        - dashboard
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges
  
networks:
  default:
    external:
      name: traefik
