version: '2'

services:
  api:
    image: vibioh/docker-api
    environment:
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      DOCKER_VERSION: '1.23'
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: docker-api.vibioh.fr'
      traefik.port: '1080'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/vibioh/code/docker-deploy/users:/users:ro
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 134217728
    security_opt:
    - no-new-privileges

  front:
    image: vibioh/docker-front
    command: -spa -domain 'docker-api.vibioh.fr fonts.gstatic.com'
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: docker.vibioh.fr, docker.l3miage.fr'
      traefik.port: '1080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik

