version: '2'

services:
  api:
    image: vibioh/dashboard-api
    command:
    - -dockerHost
    - unix:///var/run/docker.sock
    - -dockerVersion
    - '1.24'
    - -ws
    - ^dashboard(?:-api)?\.vibioh\.fr
    - -authUrl
    - http://auth:1080
    - -users
    - vibioh:admin|lili1725:multi
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: dashboard-api.vibioh.fr, dashboard-api.l3miage.fr'
      traefik.port: '1080'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
    - auth
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 33554432
    security_opt:
    - no-new-privileges

  auth:
    image: vibioh/dashboard-auth
    command:
    - -githubState
    - ${GITHUB_OAUTH_STATE}
    - -githubClientId
    - ${GITHUB_OAUTH_CLIENT_ID}
    - -githubClientSecret
    - ${GITHUB_OAUTH_CLIENT_SECRET}
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: dashboard-auth.vibioh.fr'
      traefik.port: '1080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 33554432
    security_opt:
    - no-new-privileges

  front:
    image: vibioh/dashboard-front
    command:
    - -spa
    - -env
    - API_URL,WS_URL,AUTH_URL,GITHUB_OAUTH_CLIENT_ID,GITHUB_OAUTH_STATE
    - -csp
    - "default-src 'self'; script-src 'self' 'unsafe-inline' www.google-analytics.com cdnjs.cloudflare.com ajax.googleapis.com cdn.ravenjs.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com cdnjs.cloudflare.com; font-src 'self' fonts.gstatic.com cdnjs.cloudflare.com data: ; img-src 'self' www.google-analytics.com data: ; connect-src 'self' wss: dashboard-api.vibioh.fr dashboard-auth.vibioh.fr;"
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: dashboard.vibioh.fr, dashboard.l3miage.fr'
      traefik.port: '1080'
    environment:
      API_URL: 'https://dashboard-api.vibioh.fr'
      WS_URL: 'wss://dashboard-api.vibioh.fr/ws'
      AUTH_URL: 'https://dashboard-auth.vibioh.fr'
      GITHUB_OAUTH_STATE: '${GITHUB_OAUTH_STATE}'
      GITHUB_OAUTH_CLIENT_ID: '${GITHUB_OAUTH_CLIENT_ID}'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
