version: '2'

services:
  auth:
    image: vibioh/auth
    command:
    - -tls=false
    - -basicUsers
    - admin:${ADMIN_PASSWORD}
    - -corsHeaders
    - Authorization
    - -corsCredentials
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

  api:
    image: vibioh/dashboard-api
    command:
    - -tls=false
    - -ws
    - .*
    - -dockerVersion
    - '1.24'
    - -authUrl
    - http://auth:1080
    - -users
    - admin:admin
    - -corsHeaders
    - Content-Type,Authorization
    - -corsMethods
    - GET,POST,DELETE
    - -corsCredentials
    - -csp
    - "default-src 'self'; script-src 'unsafe-inline' ajax.googleapis.com cdnjs.cloudflare.com; style-src 'unsafe-inline' cdnjs.cloudflare.com fonts.googleapis.com; font-src data: fonts.gstatic.com cdnjs.cloudflare.com; img-src data:"
    links:
    - auth
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

  front:
    image: vibioh/dashboard-front
    command:
    - -spa
    - -env
    - API_URL,WS_URL,AUTH_URL,BASIC_AUTH_ENABLED
    - -csp
    - "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' ws: api:1080 auth:1080;"
    environment:
      API_URL: 'http://api:1080'
      WS_URL: 'ws://api:1080/ws'
      AUTH_URL: 'http://auth:1080'
      BASIC_AUTH_ENABLED: 'true'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

  chrome:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444/tcp
    links:
    - auth
    - api
    - front
    volumes:
    - /dev/shm:/dev/shm
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    cpu_shares: 128
    mem_limit: 1073741824