[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/auth"

[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/httputils"

[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/mailer"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[override]]
  branch = "master"
  name = "github.com/docker/distribution"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
