#!/usr/bin/env sh

set -e

MODE="mode: atomic"

echo "${MODE}" > coverage.txt

for pkg in $(go list -e ./... | grep -v vendor | grep -v node_modules); do
    go test -covermode=atomic -coverprofile=profile.out $pkg

    if [ -f profile.out ]; then
        cat profile.out | grep --invert-match "${MODE}" >> coverage.txt || true
        rm profile.out
    fi
done

go tool cover -func=coverage.txt
